import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>meGarow|招待制画廊SNS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='l-header'></header>
      <main className='container'></main>
      <footer className='container'>
        <span className='container'>
          <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
        </span>
      </footer>
    </div>
  );
}
