import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="wrap">
      <Head>
        <title>meGarow|招待制画廊SNS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="l-header">
        <div className="l-header__wrapper">
          <div className="l-header__container">
            <h1 className="l-header__title">
              <picture className="l-header__image-inner">
                <Image
                  src="/images/white-logo.svg"
                  alt="メガロのロゴ"
                  width={183}
                  height={38}
                  className="c-image-fluid"
                />
              </picture>
            </h1>
            <button className="c-hamburger-button">
              <span className="c-hamburger-button__border"></span>
            </button>
            <nav className="l-header-navigation">
              <ul className="l-header-navigatio__inner">
                <li className="l-header-navigation__item">
                  <a href="" className="l-header-navigation__link">
                    メガロとは？
                  </a>
                </li>
                <li className="l-header-navigation__item">
                  <a href="" className="l-header-navigation__link">
                    メガロオークションについて
                  </a>
                </li>
                <li className="l-header-navigation__item">
                  <a href="" className="l-header-navigation__link">
                    メガロの今後
                  </a>
                </li>
                <li className="l-header-navigation__item">
                  <button className="c-primary-button">クリエイター登録</button>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </header>
      <main className="l-main">
        <section className="p-fv">
          <div className="p-fv__wrapper">
            <div className="p-fv__image-container">
              <picture className="p-fv__image-inner">
                <Image
                  src="/images/fv-main.png"
                  alt="制作過程を投稿"
                  width={72}
                  height={16}
                  className="c-image-fluid"
                />
              </picture>
              <picture className="p-fv__image-inner">
                <Image
                  src="/images/fv-message01.png"
                  alt="制作過程を投稿"
                  width={72}
                  height={16}
                  className="c-image-fluid"
                />
              </picture>
              <picture className="p-fv__image-inner">
                <Image
                  src="/images/fv-message02.png"
                  alt="制作過程を投稿"
                  width={72}
                  height={16}
                  className="c-image-fluid"
                />
              </picture>
              <picture className="p-fv__image-inner">
                <Image
                  src="/images/fv-message03.png"
                  alt="制作過程を投稿"
                  width={72}
                  height={16}
                  className="c-image-fluid"
                />
              </picture>
            </div>
            <div className="p-fv__title-inner">
              <h2 className="p-fv__title">
                あなたの
                <br />
                クリエイティブが
                <br />
                誰かの価値になる。
              </h2>
            </div>
            <div className="p-fv__button-inner">
              <a href="" className="c-primary-button">
                クリエイター登録はこちら
              </a>
            </div>
          </div>
        </section>
        <section className="p-introduction">
          <div className="p-introduction__wrapper">
            <div className="p-introduction__title-inner">
              <h2 className="p-introduction__title">
                <picture className="p-introduction__image-inner">
                  <Image
                    src="/images/what-megarow.svg"
                    alt="制作過程を投稿"
                    width={72}
                    height={16}
                    className="c-image-fluid"
                  />
                </picture>
              </h2>
            </div>
            <div className="p-introduction__text-inner">
              <p className="p-introduction__text">
                メガロは制作活動する、
                <br />
                クリエイター・アーティストのための画廊
                <br />
                を持つことができるサービスです。
              </p>
            </div>
          </div>
        </section>
        <section className="p-use">
          <div className="p-use__wrapper">
            <div className="p-use-title__inner">
              <h2 className="c-section-title">メガロでできること</h2>
            </div>
            <div className="p-use__container">
              <div className="p-use-card">
                <picture className="p-use-card__image-inner">
                  <Image
                    src="/images/used-image01.png"
                    alt="制作過程を投稿"
                    width={100}
                    height={100}
                    className="c-image-fluid"
                  />
                </picture>
                <div className="p-use-card__title-inner">
                  <h3 className="p-use-card__title">
                    アートを好きな人 <br />
                    クリエイターを招待
                  </h3>
                </div>
              </div>
              <div className="p-use-card">
                <picture className="p-use-card__image-inner">
                  <Image
                    src="/images/used-image02.png"
                    alt="制作過程を投稿"
                    width={100}
                    height={100}
                    className="c-image-fluid"
                  />
                </picture>
                <div className="p-use-card__title-inner">
                  <h3 className="p-use-card__title">
                    アートを好きな人 <br />
                    クリエイターを招待
                  </h3>
                </div>
              </div>
              <div className="p-use-card">
                <picture className="p-use-card__image-inner">
                  <Image
                    src="/images/used-image03.png"
                    alt="制作過程を投稿"
                    width={100}
                    height={100}
                    className="c-image-fluid"
                  />
                </picture>
                <div className="p-use-card__title-inner">
                  <h3 className="p-use-card__title">
                    アートを好きな人 <br />
                    クリエイターを招待
                  </h3>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="p-auction">
          <div className="p-auction__wrapper">
            <div className="p-auction__title-inner">
              <h2 className="c-section-title">メガロオークションとは？</h2>
            </div>
            <div className="p-auction__container">
              <picture className="p-auction__image-inner">
                <Image
                  src="/images/auction-image01.png"
                  alt="制作過程を投稿"
                  width={100}
                  height={100}
                  className="c-image-fluid"
                />
              </picture>
              <ul className="p-auction__list">
                <li className="p-auction__item">
                  <h3 className="p-auction__text">
                    投稿した作品を、
                    <br />
                    オークションに出品♪
                  </h3>
                </li>
                <li className="p-auction__item">
                  <h3 className="p-auction__text">あとは入札を待つだけ</h3>
                </li>
                <li className="p-auction__item">
                  <h3 className="p-auction__text">
                    入札価格はあなただけに公開
                  </h3>
                </li>
                <li className="p-auction__item">
                  <h3 className="p-auction__text">
                    落札者はクリエイターが決定
                  </h3>
                </li>
              </ul>
            </div>
          </div>
        </section>
        <section className="p-white-paper">
          <div className="p-white-paper__wrapper">
            <div className="p-white-paper__title-inner">
              <h2 className="c-section title" data-english-title="white paper">
                メガロの今後
              </h2>
            </div>
            <div className="p-white-paper__container">
              <div className="p-white-paper__card">
                <h3 className="p-white-paper__text">ポートフォリオ機能</h3>
              </div>
              <div className="p-white-paper__card">
                <h3 className="p-white-paper__text">ポートフォリオ機能</h3>
              </div>
            </div>
            <div className="p-white-paper__button-inner">
              <a href="" className="primary-button">
                クリエイター登録
              </a>
            </div>
          </div>
        </section>
      </main>
      <footer className="l-footer">
        <div className="l-footer__wrapper">
          <picture className="l-footer__logo-inner">
            <Image
              src="/images/white-logo.svg"
              alt="メガロロゴ"
              width={72}
              height={16}
              className="l-footer__logo"
            />
          </picture>
          <div className="l-footer__container">
            <nav className="l-footer-nav">
              <ul className="l-footer-nav__container">
                <li className="l-footer-nav__item">
                  <a href="" className="l-footer__link">
                    お問い合わせ
                  </a>
                </li>
                <li className="l-footer-nav__item">
                  <a href="" className="l-footer__link">
                    プライバシーポリシー
                  </a>
                </li>
              </ul>
            </nav>
          </div>
          <div className="l-footer__bottom">
            <p className="l-footer__copyright">
              Copyright © megarow All Rights Reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
